2021-05-18 16:34:17,799 INFO    MainThread:16860 [wandb_setup.py:_flush():69] setting env: {}
2021-05-18 16:34:17,800 INFO    MainThread:16860 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-18 16:34:17,800 ERROR   MainThread:16860 [wandb_setup.py:_flush():69] error
Traceback (most recent call last):
  File "C:\Users\Lorenzo\PycharmProjects\flow-forecast\venv\lib\site-packages\wandb\sdk\wandb_init.py", line 741, in init
    wi.setup(kwargs)
  File "C:\Users\Lorenzo\PycharmProjects\flow-forecast\venv\lib\site-packages\wandb\sdk\wandb_init.py", line 155, in setup
    wandb_login._login(anonymous=anonymous, force=force, _disable_warning=True)
  File "C:\Users\Lorenzo\PycharmProjects\flow-forecast\venv\lib\site-packages\wandb\sdk\wandb_login.py", line 216, in _login
    wlogin.prompt_api_key()
  File "C:\Users\Lorenzo\PycharmProjects\flow-forecast\venv\lib\site-packages\wandb\sdk\wandb_login.py", line 144, in prompt_api_key
    no_create=self._settings.force,
  File "C:\Users\Lorenzo\PycharmProjects\flow-forecast\venv\lib\site-packages\wandb\sdk\lib\apikey.py", line 138, in prompt_api_key
    write_key(settings, key, api=api)
  File "C:\Users\Lorenzo\PycharmProjects\flow-forecast\venv\lib\site-packages\wandb\sdk\lib\apikey.py", line 223, in write_key
    raise ValueError("API key must be 40 characters long, yours was %s" % len(key))
ValueError: API key must be 40 characters long, yours was 31
2021-05-18 16:34:17,800 INFO    MainThread:16860 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-18 16:34:17,800 INFO    MainThread:16860 [wandb_setup.py:_flush():69] setting login settings: {'api_key': 'e7db10531d60917492a41a48d803cf9aff2ee52f'}
2021-05-18 16:34:17,801 INFO    MainThread:16860 [wandb_init.py:_log_setup():336] Logging user logs to C:\Users\Lorenzo\PycharmProjects\flow-forecast\notebooks\wandb\run-20210518_163417-1k9brct8\logs\debug.log
2021-05-18 16:34:17,801 INFO    MainThread:16860 [wandb_init.py:_log_setup():337] Logging internal logs to C:\Users\Lorenzo\PycharmProjects\flow-forecast\notebooks\wandb\run-20210518_163417-1k9brct8\logs\debug-internal.log
2021-05-18 16:34:17,802 INFO    MainThread:16860 [wandb_init.py:init():369] calling init triggers
2021-05-18 16:34:17,802 INFO    MainThread:16860 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-18 16:34:17,802 INFO    MainThread:16860 [wandb_init.py:init():391] re-initializing run, found existing run on stack: 27ntobae
2021-05-18 16:34:17,803 INFO    MainThread:16860 [wandb_run.py:finish():1167] finishing run loloheia/pretrained-wind-updated/27ntobae
2021-05-18 16:34:17,805 ERROR   MainThread:16860 [jupyter.py:save_history():312] Run pip install nbformat to save notebook history
2021-05-18 16:34:17,805 INFO    MainThread:16860 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-18 16:34:17,806 INFO    MainThread:16860 [wandb_init.py:_jupyter_teardown():268] cleaning up jupyter logic
2021-05-18 16:34:17,806 INFO    MainThread:16860 [wandb_run.py:_atexit_cleanup():1494] got exitcode: 0
2021-05-18 16:34:17,806 INFO    MainThread:16860 [wandb_run.py:_restore():1466] restore
2021-05-18 16:34:18,298 INFO    MainThread:16860 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 935
  total_bytes: 935
}

2021-05-18 16:34:18,438 INFO    MainThread:16860 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 935
  total_bytes: 935
}

2021-05-18 16:34:19,336 INFO    MainThread:16860 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 935
  total_bytes: 3585
}

2021-05-18 16:34:21,711 INFO    MainThread:16860 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3587
  total_bytes: 3587
}

2021-05-18 16:34:21,821 INFO    MainThread:16860 [wandb_run.py:_wait_for_finish():1616] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3587
  total_bytes: 3587
}

2021-05-18 16:34:22,927 INFO    MainThread:16860 [wandb_run.py:_show_files():1838] logging synced files
2021-05-18 16:34:22,934 INFO    MainThread:16860 [wandb_init.py:init():418] starting backend
2021-05-18 16:34:22,934 INFO    MainThread:16860 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=spawn, using: spawn
2021-05-18 16:34:22,937 INFO    MainThread:16860 [backend.py:ensure_launched():123] starting backend process...
2021-05-18 16:34:23,028 INFO    MainThread:16860 [backend.py:ensure_launched():128] started backend process with pid: 6776
2021-05-18 16:34:23,028 INFO    MainThread:16860 [wandb_init.py:init():423] backend started and connected
2021-05-18 16:34:23,028 INFO    MainThread:16860 [wandb_init.py:init():465] updated telemetry
2021-05-18 16:34:23,028 INFO    MainThread:16860 [wandb_init.py:init():484] communicating current version
2021-05-18 16:34:24,100 INFO    MainThread:16860 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.30 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-05-18 16:34:24,104 INFO    MainThread:16860 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-18 16:34:24,608 INFO    MainThread:16860 [wandb_init.py:init():522] starting run threads in backend
2021-05-18 16:34:24,817 INFO    MainThread:16860 [wandb_run.py:_console_start():1524] atexit reg
2021-05-18 16:34:24,818 INFO    MainThread:16860 [wandb_run.py:_redirect():1371] redirect: SettingsConsole.WRAP
2021-05-18 16:34:24,819 INFO    MainThread:16860 [wandb_run.py:_redirect():1414] Wrapping output streams.
2021-05-18 16:34:24,819 INFO    MainThread:16860 [wandb_run.py:_redirect():1438] Redirects installed.
2021-05-18 16:34:24,819 INFO    MainThread:16860 [wandb_init.py:init():546] run started, returning control to user process
2021-05-18 16:34:29,539 INFO    MainThread:16860 [wandb_watch.py:watch():39] Watching
2021-05-18 16:37:15,790 INFO    MainThread:16860 [wandb_setup.py:_flush():69] setting env: {}
2021-05-18 16:37:15,791 INFO    MainThread:16860 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-18 16:37:15,791 ERROR   MainThread:16860 [wandb_setup.py:_flush():69] error
Traceback (most recent call last):
  File "C:\Users\Lorenzo\PycharmProjects\flow-forecast\venv\lib\site-packages\wandb\sdk\wandb_init.py", line 741, in init
    wi.setup(kwargs)
  File "C:\Users\Lorenzo\PycharmProjects\flow-forecast\venv\lib\site-packages\wandb\sdk\wandb_init.py", line 155, in setup
    wandb_login._login(anonymous=anonymous, force=force, _disable_warning=True)
  File "C:\Users\Lorenzo\PycharmProjects\flow-forecast\venv\lib\site-packages\wandb\sdk\wandb_login.py", line 216, in _login
    wlogin.prompt_api_key()
  File "C:\Users\Lorenzo\PycharmProjects\flow-forecast\venv\lib\site-packages\wandb\sdk\wandb_login.py", line 144, in prompt_api_key
    no_create=self._settings.force,
  File "C:\Users\Lorenzo\PycharmProjects\flow-forecast\venv\lib\site-packages\wandb\sdk\lib\apikey.py", line 138, in prompt_api_key
    write_key(settings, key, api=api)
  File "C:\Users\Lorenzo\PycharmProjects\flow-forecast\venv\lib\site-packages\wandb\sdk\lib\apikey.py", line 223, in write_key
    raise ValueError("API key must be 40 characters long, yours was %s" % len(key))
ValueError: API key must be 40 characters long, yours was 31
2021-05-18 16:37:15,791 INFO    MainThread:16860 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-18 16:37:15,791 INFO    MainThread:16860 [wandb_setup.py:_flush():69] setting login settings: {'api_key': 'e7db10531d60917492a41a48d803cf9aff2ee52f'}
2021-05-18 16:37:15,792 INFO    MainThread:16860 [wandb_init.py:_log_setup():336] Logging user logs to C:\Users\Lorenzo\PycharmProjects\flow-forecast\notebooks\wandb\run-20210518_163715-79906w7h\logs\debug.log
2021-05-18 16:37:15,792 INFO    MainThread:16860 [wandb_init.py:_log_setup():337] Logging internal logs to C:\Users\Lorenzo\PycharmProjects\flow-forecast\notebooks\wandb\run-20210518_163715-79906w7h\logs\debug-internal.log
2021-05-18 16:37:15,792 INFO    MainThread:16860 [wandb_init.py:_jupyter_setup():287] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001D990FE30C8>
2021-05-18 16:37:15,792 INFO    MainThread:16860 [wandb_init.py:init():369] calling init triggers
2021-05-18 16:37:15,792 INFO    MainThread:16860 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-18 16:37:15,792 INFO    MainThread:16860 [wandb_init.py:init():391] re-initializing run, found existing run on stack: 1k9brct8
2021-05-18 16:37:15,794 INFO    MainThread:16860 [wandb_run.py:finish():1167] finishing run loloheia/pretrained-wind-updated/1k9brct8
